// <auto-generated />
using System;
using BlazorSyncfusion.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorSyncfusion.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230515164519_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorSyncfusion.Shared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3871),
                            FirstName = "Kenneth",
                            IsEmployee = true,
                            LastName = "Hougaard Soerensen",
                            Mail = "keso@aspit.dk",
                            NickName = "KESO",
                            School = "AspIT Trekanten",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3919),
                            FirstName = "Mads",
                            IsEmployee = true,
                            LastName = "Mikkel Rasmussen",
                            Mail = "mara@aspit.dk",
                            NickName = "MARA",
                            School = "AspIT Trekanten",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3923),
                            FirstName = "Dea",
                            IsEmployee = true,
                            LastName = "Gram",
                            Mail = "degr@aspin.dk",
                            NickName = "DEGR",
                            School = "AspIN",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3925),
                            FirstName = "Jan",
                            IsEmployee = true,
                            LastName = "Lindgaard Pedersen",
                            Mail = "jape@aspin.dk",
                            NickName = "JAPE",
                            School = "AspIN",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3928),
                            FirstName = "Jesper",
                            IsEmployee = true,
                            LastName = "Lade Mathiesen",
                            Mail = "jema@aspit.dk",
                            NickName = "JEMA",
                            Phone = "+45 72 16 28 56",
                            School = "AspIT Trekanten",
                            Title = "Specialpædagogisk vejleder"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3931),
                            FirstName = "Henrik",
                            IsEmployee = true,
                            LastName = "Stephansen",
                            Mail = "hens@aspit.dk",
                            NickName = "HENS",
                            Phone = "+45 72 16 26 85",
                            School = "AspIT Trekanten",
                            Title = "Praktik- og jobvejleder"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(3933),
                            FirstName = "Ole",
                            IsEmployee = true,
                            LastName = "Bay Jensen",
                            Mail = "oje@aspit.dk",
                            NickName = "OJE",
                            Phone = "+45 72 16 27 99",
                            School = "AspIT Trekanten",
                            Title = "Uddannelseschef"
                        });
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(4050),
                            TeacherId = 5,
                            Text = "ADHD child and very annoying."
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 15, 18, 45, 18, 926, DateTimeKind.Local).AddTicks(4054),
                            TeacherId = 1,
                            Text = "funny."
                        });
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Note", b =>
                {
                    b.HasOne("BlazorSyncfusion.Shared.Employee", "Teacher")
                        .WithMany("Notes")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Employee", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
