// <auto-generated />
using System;
using FullStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullStack.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullStack.Shared.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Rockstar Games is a video game publisher that is a wholly owned subsidiary of Take-Two Interactive. The publisher is known for the Grand Theft Auto, Max Payne, and Red Dead series.",
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Mojang Studios is a Swedish video game developer and a studio of Xbox Game Studios based in Stockholm. It was founded by Markus Persson in 2009 as Mojang Specifications, inheriting the name from a previous video game venture he left two years prior.",
                            Name = "Mojang"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "CD Projekt S.A. is a Polish video game developer, publisher and distributor based in Warsaw, founded in May 1994 by Marcin Iwiński and Michał Kiciński. They are mostly known for their The Witcher series.",
                            Name = "CD Projekt"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Quantic Dream S.A. is a French video game developer and publisher based in Paris. Founded in May 1997, Quantic Dream is known for its interactive drama story driven games such as Heavy Rain, Beyond: Two Souls, and Detroit: Become Human.",
                            Name = "Quantic Dream"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Santa Monica Studio is an American video game developer and part of SIE Worldwide Studios, which is owned by Sony Interactive Entertainment. They are known for their God of War series.",
                            Name = "Santa Monica Studio"
                        });
                });

            modelBuilder.Entity("FullStack.Shared.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PublisherId = 1,
                            ReleaseYear = 2013,
                            Title = "Grand Theft Auto 5"
                        },
                        new
                        {
                            Id = 2,
                            PublisherId = 1,
                            ReleaseYear = 2018,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 3,
                            PublisherId = 1,
                            ReleaseYear = 2025,
                            Title = "Grand Theft Auto 6"
                        },
                        new
                        {
                            Id = 4,
                            PublisherId = 2,
                            ReleaseYear = 2011,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 5,
                            PublisherId = 3,
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 6,
                            PublisherId = 4,
                            ReleaseYear = 2018,
                            Title = "Detroit: Become Human"
                        },
                        new
                        {
                            Id = 7,
                            PublisherId = 5,
                            ReleaseYear = 2022,
                            Title = "God of War Ragnarök"
                        },
                        new
                        {
                            Id = 8,
                            PublisherId = 3,
                            ReleaseYear = 2015,
                            Title = "The Witcher 3"
                        });
                });

            modelBuilder.Entity("FullStack.Shared.Entities.VideoGame", b =>
                {
                    b.HasOne("FullStack.Shared.Entities.Publisher", "Publisher")
                        .WithMany("VideoGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("FullStack.Shared.Entities.Publisher", b =>
                {
                    b.Navigation("VideoGames");
                });
#pragma warning restore 612, 618
        }
    }
}
