// <auto-generated />
using System;
using AntiForgery.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntiForgery.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AntiForgery.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2022, 1, 8),
                            Summary = "Freezing",
                            TemperatureC = -13
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2022, 1, 9),
                            Summary = "Chilly",
                            TemperatureC = -2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2022, 1, 10),
                            Summary = "Freezing",
                            TemperatureC = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2022, 1, 17),
                            Summary = "Balmy",
                            TemperatureC = -16
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2022, 1, 19),
                            Summary = "Bracing",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2022, 1, 22),
                            Summary = "Chilly",
                            TemperatureC = -2
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2022, 1, 24),
                            Summary = "Freezing",
                            TemperatureC = -13
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2022, 1, 25),
                            Summary = "Bracing",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2022, 2, 6),
                            Summary = "Balmy",
                            TemperatureC = -16
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2022, 2, 7),
                            Summary = "Freezing",
                            TemperatureC = -13
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2022, 2, 9),
                            Summary = "Freezing",
                            TemperatureC = 1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2022, 2, 12),
                            Summary = "Bracing",
                            TemperatureC = 14
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2022, 2, 16),
                            Summary = "Chilly",
                            TemperatureC = -2
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2022, 2, 22),
                            Summary = "Balmy",
                            TemperatureC = -16
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
